### ISSUE TITLE
IE Support, more graceful degrading

### ISSUE THREAD

**Issue by n8han** [foundweekends/pamflet#4]
Pamflets are illegible on IE 7 and use the mobile stylesheet is used on IE 8. If you force IE 8 to use the desktop stylesheet it looks broken, though it is legible.

The default desktop stylesheet should not be so brittle.

**Comment by eed3si9n** [comment]
I'm guessing these "sbt" tagged tasks were demands by early sbt team to adopt Pamflet?
I think we can dissolve these ransom notes since I've adopted Pamflet for sbt website back in 2014 - sbt/website@57bb93275be27eb6c2a58348204bacf1a0a5f90d
Also IE 7.
