### ISSUE TITLE
Publish to github pages

### ISSUE THREAD

**Issue by n8han** [foundweekends/pamflet#6]
The `pf` tool should be able to automatically commit to a `gh-pages` branch for easy publishing through github pages.

**Comment by DeaconDesperado** [comment]
I realize this issue is old as heck, but for those inbound from google, [this plugin](https://github.com/sbt/sbt-ghpages) works great!

**Comment by eed3si9n** [comment]
Yea. With sbt-site and sbt-ghpages, you can build pamflet and push it to Github in a single task from sbt.
