### ISSUE TITLE
publish documents to new site

### ISSUE THREAD

**Issue by xuwei-k** [foundweekends/pamflet#74]
- http://www.foundweekends.org/pamflet ?
- `gh-pages` branch of https://github.com/foundweekends/pamflet ?
- any other ?

**Comment by xuwei-k** [comment]
done

- https://github.com/foundweekends/pamflet/compare/foundweekends:86fc7d6...foundweekends:12954ea
- https://github.com/foundweekends/pamflet/tree/gh-pages
- http://www.foundweekends.org/pamflet/Pamflet

**Comment by eed3si9n** [comment]
could we please use `index.html` so it's http://www.foundweekends.org/pamflet?

**Comment by eed3si9n** [comment]
https://github.com/foundweekends/pamflet/pull/75
